const prefix = 'WALLET';

export const WALLET_TYPES = {
  WALLET_LIST_START: `${prefix}_LIST_START`,
  WALLET_LIST_SUCCESS: `${prefix}_LIST_SUCCESS`,
  WALLET_LIST_ERROR: `${prefix}_LIST_ERROR`,

  WALLET_DEPOSIT_ADDRESS_START: `${prefix}_DEPOSIT_ADDRESS_LIST_START`,
  WALLET_DEPOSIT_ADDRESS_SUCCESS: `${prefix}_DEPOSIT_ADDRESS_LIST_SUCCESS`,
  WALLET_DEPOSIT_ADDRESS_ERROR: `${prefix}_DEPOSIT_ADDRESS_LIST_ERROR`,
};
